import { PrismaClient, UserRole, VerificationStatus } from '@prisma/client';

const prisma = new PrismaClient();

const newSuppliersData = [
  {
    user: {
      email: 'contact@sahel-agro.com',
      supabaseUid: 'supabase-uid-sahel-agro',
      firstName: 'Oumar',
      lastName: 'Coulibaly',
      role: UserRole.SUPPLIER,
    },
    company: {
      companyName: 'Sahel Agro-Industrie SA',
      country: 'Mali',
      city: 'Bamako',
      registrationNumber: 'ML-BMK-2022-B-4921',
      sector: 'Agroalimentaire',
      description: 'Transformateur et exportateur majeur de fruits séchés, graines d\'oléagineux et épices du Sahel certifiés Bio.',
      website: 'https://sahel-agro.com',
      phone: '+223 20 22 34 56',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date(),
      verificationNotes: 'Registre du commerce Mali et certification Bio ECOCERT validés.',
    },
    products: [
      {
        title: 'Mangues Séchées Amélie Bio (Cartons de 10kg)',
        slug: 'mangues-sechees-amelie-bio-10kg',
        description: 'Lamelles de mangues biologiques séchées à doux soleil, sans aucun sucre ajouté ni conservateur. Qualité export supérieure.',
        category: 'Agroalimentaire',
        priceMin: 6.5,
        priceMax: 8.2,
        currency: 'EUR',
        moq: 10,
        unit: 'carton (10kg)',
        originCountry: 'Mali',
        images: ['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Sésame Blanc Décortiqué Grade A (Sacs 50kg)',
        slug: 'sesame-blanc-decortique-grade-a-50kg',
        description: 'Graines de sésame blanc pur à 99.9%, décortiquées et nettoyées mécano-optiquement. Idéal pour boulangerie et huilerie.',
        category: 'Agroalimentaire',
        priceMin: 1.4,
        priceMax: 1.8,
        currency: 'EUR',
        moq: 20,
        unit: 'sac (50kg)',
        originCountry: 'Mali',
        images: ['https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Poudre de Baobab Pur (Pain de Singe) - 20kg',
        slug: 'poudre-de-baobab-pur-20kg',
        description: 'Superaliment 100% naturel, riche en vitamine C, fibres et calcium. Extraction mécanique sans traitement chimique.',
        category: 'Agroalimentaire',
        priceMin: 4.8,
        priceMax: 6.5,
        currency: 'EUR',
        moq: 5,
        unit: 'sac (20kg)',
        originCountry: 'Mali',
        images: ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Fleurs d\'Hibiscus Séchées (Bissap Rouge) - 25kg',
        slug: 'fleurs-hibiscus-sechees-bissap-25kg',
        description: 'Fleurs de Bissap rouge foncé (Hibiscus Sabdariffa) de qualité premium. Taux d\'humidité < 10%, sans résidus.',
        category: 'Agroalimentaire',
        priceMin: 2.2,
        priceMax: 3.1,
        currency: 'EUR',
        moq: 8,
        unit: 'sac (25kg)',
        originCountry: 'Mali',
        images: ['https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Noix de Anacarde Brutes (RCN 48-50 lbs)',
        slug: 'noix-de-anacarde-brutes-rcn-48-50',
        description: 'Noix de cajou brutes en coque, récolte fraîche. Outturn 48-50 lbs, nut count 180-200/kg.',
        category: 'Agroalimentaire',
        priceMin: 1.1,
        priceMax: 1.45,
        currency: 'EUR',
        moq: 100,
        unit: 'kg',
        originCountry: 'Mali',
        images: ['https://images.unsplash.com/photo-1509358271058-acd01cc9386a?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
    ],
  },
  {
    user: {
      email: 'sales@atlas-botanicals.ma',
      supabaseUid: 'supabase-uid-atlas-botanicals',
      firstName: 'Yassine',
      lastName: 'El Amrani',
      role: UserRole.SUPPLIER,
    },
    company: {
      companyName: 'Atlas Botanicals Morocco',
      country: 'Maroc',
      city: 'Agadir',
      registrationNumber: 'MA-AGA-2019-B-8812',
      sector: 'Cosmétique & Soins',
      description: 'Laboratoire spécialisé dans l\'extraction d\'huiles précieuses et d\'ingrédients dermocosmétiques issus de la flore marocaine.',
      website: 'https://atlas-botanicals.ma',
      phone: '+212 528 84 12 90',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date(),
      verificationNotes: 'Patente marocaine et certification ISO 22716 / ECOCERT vérifiées.',
    },
    products: [
      {
        title: 'Huile d\'Argan Bio Pression à Froid (Bidons 25L)',
        slug: 'huile-argan-bio-pression-froid-25l',
        description: 'Huile d\'argan kosmetique 100% pure et biologique, pressée à froid dans nos coopératives certifiées d\'Agadir.',
        category: 'Cosmétique & Soins',
        priceMin: 22.0,
        priceMax: 28.0,
        currency: 'EUR',
        moq: 2,
        unit: 'bidon (25L)',
        originCountry: 'Maroc',
        images: ['https://images.unsplash.com/photo-1608248597359-54d922336336?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Huile de Pépins de Figue de Barbarie Pure (1L)',
        slug: 'huile-pepins-figue-de-barbarie-pure-1l',
        description: 'Elixir anti-âge exceptionnel. Rendement d\'1 tonne de fruits pour 1L d\'huile. Taux d\'acide linoléique > 60%.',
        category: 'Cosmétique & Soins',
        priceMin: 350.0,
        priceMax: 420.0,
        currency: 'EUR',
        moq: 1,
        unit: 'flacon (1L)',
        originCountry: 'Maroc',
        images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Eau de Rose de Kelaat M\'Gouna (Fûts de 50L)',
        slug: 'eau-de-rose-kelaat-mgouna-50l',
        description: 'Hydrolat de Rose Damascena pur issu de la distillation artisanale de la Vallée des Roses.',
        category: 'Cosmétique & Soins',
        priceMin: 4.5,
        priceMax: 6.0,
        currency: 'EUR',
        moq: 2,
        unit: 'fût (50L)',
        originCountry: 'Maroc',
        images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Savon Noir Beldi à l\'Eucalyptus (Seaux 10kg)',
        slug: 'savon-noir-beldi-eucalyptus-10kg',
        description: 'Pâte lavante traditionnelle à base d\'huile d\'olive noire saponifiée et enrichie en huile essentielle d\'eucalyptus.',
        category: 'Cosmétique & Soins',
        priceMin: 3.2,
        priceMax: 4.5,
        currency: 'EUR',
        moq: 5,
        unit: 'seau (10kg)',
        originCountry: 'Maroc',
        images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Argile Ghassoul Naturelle en Poudre (25kg)',
        slug: 'argile-ghassoul-naturelle-poudre-25kg',
        description: 'Argile saponifère unique extraite du Moyen Atlas. Idéale pour masques capillaires et soins purifiants du corps.',
        category: 'Cosmétique & Soins',
        priceMin: 2.8,
        priceMax: 3.9,
        currency: 'EUR',
        moq: 4,
        unit: 'sac (25kg)',
        originCountry: 'Maroc',
        images: ['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
    ],
  },
  {
    user: {
      email: 'export@ivoire-cacao.ci',
      supabaseUid: 'supabase-uid-ivoire-cacao',
      firstName: 'Koffi',
      lastName: 'Brou',
      role: UserRole.SUPPLIER,
    },
    company: {
      companyName: 'Ivoire Cacao & Épices SARL',
      country: 'Côte d\'Ivoire',
      city: 'Abidjan',
      registrationNumber: 'CI-ABJ-2018-B-1104',
      sector: 'Agroalimentaire & Négoce',
      description: 'Négociant et transformateur de dérivés de cacao, café robusta et épices fines de Côte d\'Ivoire.',
      website: 'https://ivoire-cacao.ci',
      phone: '+225 27 21 35 48 90',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date(),
      verificationNotes: 'Agreements Ministère du Commerce et Conseil Café Cacao validés.',
    },
    products: [
      {
        title: 'Fèves de Cacao Fermentées Grade 1 (Sacs 65kg)',
        slug: 'feves-de-cacao-fermentees-grade-1-65kg',
        description: 'Fèves de cacao bien fermentées et séchées au soleil, grainage 95-100 fèves/100g. Humidité < 7.5%.',
        category: 'Agroalimentaire & Négoce',
        priceMin: 3.8,
        priceMax: 4.6,
        currency: 'EUR',
        moq: 15,
        unit: 'sac (65kg)',
        originCountry: 'Côte d\'Ivoire',
        images: ['https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Poudre de Cacao Alcalinisée 10-12% (Sacs 25kg)',
        slug: 'poudre-de-cacao-alcalinisee-25kg',
        description: 'Poudre de cacao pur traitée à l\'alcali, couleur brune intense, idéal pour chocolaterie, pâtisserie et boissons.',
        category: 'Agroalimentaire & Négoce',
        priceMin: 4.2,
        priceMax: 5.5,
        currency: 'EUR',
        moq: 10,
        unit: 'sac (25kg)',
        originCountry: 'Côte d\'Ivoire',
        images: ['https://images.unsplash.com/photo-1587132137056-bfbf0166836e?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Beurre de Cacao Pur Pression à Froid (Blocs 25kg)',
        slug: 'beurre-de-cacao-pur-blocs-25kg',
        description: 'Beurre de cacao naturel désodorisé en bloc de 25kg, parfait pour cosmétique naturelle ou chocolaterie fine.',
        category: 'Agroalimentaire & Négoce',
        priceMin: 9.0,
        priceMax: 11.5,
        currency: 'EUR',
        moq: 4,
        unit: 'carton (25kg)',
        originCountry: 'Côte d\'Ivoire',
        images: ['https://images.unsplash.com/photo-1548907040-4baa42d10919?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Café Robusta Supérieur Vert (Sacs 60kg)',
        slug: 'cafe-robusta-superieur-vert-60kg',
        description: 'Grains de café Robusta vert grade 1, récolte sélective, trié à la main. Arômes boisés et corps corsé.',
        category: 'Agroalimentaire & Négoce',
        priceMin: 2.9,
        priceMax: 3.7,
        currency: 'EUR',
        moq: 20,
        unit: 'sac (60kg)',
        originCountry: 'Côte d\'Ivoire',
        images: ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Poivre Noir d\'Attiégouakro Séché (Cartons 15kg)',
        slug: 'poivre-noir-attiegouakro-seche-15kg',
        description: 'Poivre noir en grains entiers à forte teneur en pipérine, arôme puissant et piquance équilibrée.',
        category: 'Agroalimentaire & Négoce',
        priceMin: 7.5,
        priceMax: 9.8,
        currency: 'EUR',
        moq: 5,
        unit: 'carton (15kg)',
        originCountry: 'Côte d\'Ivoire',
        images: ['https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
    ],
  },
  {
    user: {
      email: 'contact@terroirtextile.bj',
      supabaseUid: 'supabase-uid-terroir-textile',
      firstName: 'Angèle',
      lastName: 'Dossou',
      role: UserRole.SUPPLIER,
    },
    company: {
      companyName: 'Terroir Textile & Artisans du Bénin',
      country: 'Bénin',
      city: 'Cotonou',
      registrationNumber: 'BJ-COT-2020-B-7743',
      sector: 'Textile & Mode',
      description: 'Manufacture textile regroupant maîtres tisseurs et teinturiers d\'Afrique de l\'Ouest pour la confection de tissus éthiques.',
      website: 'https://terroirtextile.bj',
      phone: '+229 21 32 67 89',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date(),
      verificationNotes: 'Certificat d\'origine et accréditation artisanale béninoise vérifiés.',
    },
    products: [
      {
        title: 'Tissu Pagne WAX Véritable 100% Coton (Rouleaux 12 yards)',
        slug: 'tissu-pagne-wax-veritable-12-yards',
        description: 'Véritable Wax imprimé grand teint sur coton lourd 140g/m². Motifs traditionnels et contemporains vibrants.',
        category: 'Textile & Mode',
        priceMin: 32.0,
        priceMax: 45.0,
        currency: 'EUR',
        moq: 5,
        unit: 'rouleau (12 yards)',
        originCountry: 'Bénin',
        images: ['https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Fil de Coton Écologique Filé Main (Echeveaux 5kg)',
        slug: 'fil-de-coton-ecologique-file-main-5kg',
        description: 'Fil de coton pur brut non blanchi filé au rouet traditionnel par des coopératives de femmes.',
        category: 'Textile & Mode',
        priceMin: 12.5,
        priceMax: 16.0,
        currency: 'EUR',
        moq: 4,
        unit: 'lot (5kg)',
        originCountry: 'Bénin',
        images: ['https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Tissu Kente Traditionnel Tissé Main (Bandes de 10m)',
        slug: 'tissu-kente-traditionnel-tisse-main-10m',
        description: 'Bandes de tissu Kanvo/Kente tissées à la main avec du fil de coton teint naturellement.',
        category: 'Textile & Mode',
        priceMin: 65.0,
        priceMax: 85.0,
        currency: 'EUR',
        moq: 2,
        unit: 'pièce (10m)',
        originCountry: 'Bénin',
        images: ['https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Sacs Cabas en Jute et Cuir Artisanal (Lot de 50)',
        slug: 'sacs-cabas-jute-cuir-artisanal-lot-50',
        description: 'Cabas écoresponsables solides en fibre de jute naturelle avec poignées en cuir véritable tanné végétal.',
        category: 'Textile & Mode',
        priceMin: 8.5,
        priceMax: 12.0,
        currency: 'EUR',
        moq: 50,
        unit: 'sac',
        originCountry: 'Bénin',
        images: ['https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Bazin Riche Teinté Artisanalement (Rouleaux 5m)',
        slug: 'bazin-riche-teinte-artisanalement-5m',
        description: 'Bazin 100% coton égyptien damassé et teint à la main selon la technique du batik/réserve à la cire.',
        category: 'Textile & Mode',
        priceMin: 48.0,
        priceMax: 62.0,
        currency: 'EUR',
        moq: 3,
        unit: 'rouleau (5m)',
        originCountry: 'Bénin',
        images: ['https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
    ],
  },
  {
    user: {
      email: 'info@kilimanjaro-oils.co.tz',
      supabaseUid: 'supabase-uid-kilimanjaro-oils',
      firstName: 'Grace',
      lastName: 'Mollel',
      role: UserRole.SUPPLIER,
    },
    company: {
      companyName: 'Kilimanjaro Essential Oils Ltd',
      country: 'Tanzanie',
      city: 'Arusha',
      registrationNumber: 'TZ-ARS-2021-B-3310',
      sector: 'Cosmétique & Soins',
      description: 'Producteur et distillateur d\'huiles essentielles d\'altitude, épices et extraits végétaux rares d\'Afrique de l\'Est.',
      website: 'https://kilimanjaro-oils.co.tz',
      phone: '+255 27 254 88 11',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date(),
      verificationNotes: 'Tanzania Bureau of Standards (TBS) et agrément export biologique validés.',
    },
    products: [
      {
        title: 'Huile Essentielle de Clou de Girofle de Zanzibar (5L)',
        slug: 'huile-essentielle-clou-de-girofle-zanzibar-5l',
        description: 'Huile essentielle 100% pure et naturelle issue des clous de girofle de l\'archipel de Zanzibar. Taux d\'eugénol > 82%.',
        category: 'Cosmétique & Soins',
        priceMin: 45.0,
        priceMax: 58.0,
        currency: 'EUR',
        moq: 1,
        unit: 'flacon (5L)',
        originCountry: 'Tanzanie',
        images: ['https://images.unsplash.com/photo-1608248597359-54d922336336?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Huile de Moringa Bio Extraite à Froid (10L)',
        slug: 'huile-de-moringa-bio-extraite-a-froid-10l',
        description: 'Huile de graines de Moringa Oleifera d\'altitude. Très stable, riche en acide oléique et antioxydants.',
        category: 'Cosmétique & Soins',
        priceMin: 28.0,
        priceMax: 36.0,
        currency: 'EUR',
        moq: 2,
        unit: 'bidon (10L)',
        originCountry: 'Tanzanie',
        images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Extrait de Vanille Bourbon Pure de Tanzanie (1L)',
        slug: 'extrait-de-vanille-bourbon-pure-tanzanie-1l',
        description: 'Extrait concentré de gousses de vanille Planifolia sans alcool ajouté. Taux de vanilline > 2.0%.',
        category: 'Cosmétique & Soins',
        priceMin: 120.0,
        priceMax: 150.0,
        currency: 'EUR',
        moq: 1,
        unit: 'bouteille (1L)',
        originCountry: 'Tanzanie',
        images: ['https://images.unsplash.com/photo-1509358271058-acd01cc9386a?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Poudre de Maca Bio des Hauts Plateaux (20kg)',
        slug: 'poudre-de-maca-bio-hauts-plateaux-20kg',
        description: 'Poudre de maca adaptogène séchée au soleil, riche en nutriments et minéraux.',
        category: 'Cosmétique & Soins',
        priceMin: 8.5,
        priceMax: 11.2,
        currency: 'EUR',
        moq: 3,
        unit: 'sac (20kg)',
        originCountry: 'Tanzanie',
        images: ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
      {
        title: 'Beurre de Mafura Pur Brut (Seaux 15kg)',
        slug: 'beurre-de-mafura-pur-brut-15kg',
        description: 'Beurre végétal nourrissant extrait des graines de Trichilia emetica. Riche en acides gras essentiels et limonoïdes.',
        category: 'Cosmétique & Soins',
        priceMin: 11.0,
        priceMax: 14.5,
        currency: 'EUR',
        moq: 2,
        unit: 'seau (15kg)',
        originCountry: 'Tanzanie',
        images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=800'],
        isPublished: true,
      },
    ],
  },
];

async function main() {
  console.log('Amorçage de la base de données Lougara B2B...');

  // Création d'un administrateur Lougara
  await prisma.user.upsert({
    where: { email: 'admin@lougara.com' },
    update: {},
    create: {
      supabaseUid: 'supabase-admin-mock-uid',
      email: 'admin@lougara.com',
      role: UserRole.ADMIN,
      firstName: 'Admin',
      lastName: 'Lougara',
    },
  });

  // Création d'un fournisseur vérifié pilote (Sénégal - Cosmétique & Karité)
  const supplierUser = await prisma.user.upsert({
    where: { email: 'contact@africabio-extracts.com' },
    update: {},
    create: {
      supabaseUid: 'supabase-supplier-mock-uid',
      email: 'contact@africabio-extracts.com',
      role: UserRole.SUPPLIER,
      firstName: 'Amina',
      lastName: 'Diop',
    },
  });

  const supplierProfile = await prisma.companyProfile.upsert({
    where: { userId: supplierUser.id },
    update: {},
    create: {
      userId: supplierUser.id,
      companyName: 'Africa Bio Extracts SARL',
      country: 'Sénégal',
      city: 'Dakar',
      registrationNumber: 'SN-DKR-2021-B-1284',
      sector: 'Cosmétique & Soins',
      description: 'Producteur et grossiste d\'ingrédients naturels certifiés : Beurre de karité pur, huile de baobab et moringa.',
      website: 'https://africabio-extracts.com',
      phone: '+221 77 123 45 67',
      verificationStatus: VerificationStatus.VERIFIED,
      verifiedAt: new Date(),
      verificationNotes: 'Dossier RCCM et NINEA validés par l\'administration Lougara',
    },
  });

  // Création de produits pour ce fournisseur pilote
  await prisma.product.upsert({
    where: { slug: 'beurre-de-karite-bio-brut-25kg' },
    update: {},
    create: {
      companyId: supplierProfile.id,
      title: 'Beurre de Karité Bio Brut (Fûts de 25kg)',
      slug: 'beurre-de-karite-bio-brut-25kg',
      description: 'Beurre de karité 100% naturel, non raffiné, extrait mécaniquement par coopérative féminine. Analyse qualité disponible.',
      category: 'Cosmétique & Soins',
      priceMin: 8.5,
      priceMax: 12.0,
      currency: 'EUR',
      moq: 4, // 100kg minimum
      unit: 'fût (25kg)',
      originCountry: 'Sénégal',
      images: [
        'https://images.unsplash.com/photo-1608248597359-54d922336336?auto=format&fit=crop&q=80&w=800',
      ],
      isPublished: true,
    },
  });

  // Insertion des 5 nouveaux fournisseurs
  for (const item of newSuppliersData) {
    const user = await prisma.user.upsert({
      where: { email: item.user.email },
      update: {
        firstName: item.user.firstName,
        lastName: item.user.lastName,
        role: item.user.role,
      },
      create: {
        email: item.user.email,
        supabaseUid: item.user.supabaseUid,
        firstName: item.user.firstName,
        lastName: item.user.lastName,
        role: item.user.role,
      },
    });

    const company = await prisma.companyProfile.upsert({
      where: { userId: user.id },
      update: {
        companyName: item.company.companyName,
        country: item.company.country,
        city: item.company.city,
        registrationNumber: item.company.registrationNumber,
        sector: item.company.sector,
        description: item.company.description,
        website: item.company.website,
        phone: item.company.phone,
        verificationStatus: item.company.verificationStatus,
        verifiedAt: item.company.verifiedAt,
        verificationNotes: item.company.verificationNotes,
      },
      create: {
        userId: user.id,
        companyName: item.company.companyName,
        country: item.company.country,
        city: item.company.city,
        registrationNumber: item.company.registrationNumber,
        sector: item.company.sector,
        description: item.company.description,
        website: item.company.website,
        phone: item.company.phone,
        verificationStatus: item.company.verificationStatus,
        verifiedAt: item.company.verifiedAt,
        verificationNotes: item.company.verificationNotes,
      },
    });

    for (const prod of item.products) {
      await prisma.product.upsert({
        where: { slug: prod.slug },
        update: {
          companyId: company.id,
          title: prod.title,
          description: prod.description,
          category: prod.category,
          priceMin: prod.priceMin,
          priceMax: prod.priceMax,
          currency: prod.currency,
          moq: prod.moq,
          unit: prod.unit,
          originCountry: prod.originCountry,
          images: prod.images,
          isPublished: prod.isPublished,
        },
        create: {
          companyId: company.id,
          title: prod.title,
          slug: prod.slug,
          description: prod.description,
          category: prod.category,
          priceMin: prod.priceMin,
          priceMax: prod.priceMax,
          currency: prod.currency,
          moq: prod.moq,
          unit: prod.unit,
          originCountry: prod.originCountry,
          images: prod.images,
          isPublished: prod.isPublished,
        },
      });
    }
  }

  console.log('Amorçage Lougara terminé avec succès ! 6 fournisseurs et 26 articles au total.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
